#!/usr/bin/env python3
"""Generate docs/adr/README.md from the ADR frontmatter, and validate it.

The index is generated, never hand-edited (ADR 0000). This script also enforces
every rule a SINGLE SNAPSHOT of the tree can decide, because a rule nothing checks
is a suggestion:

  - `id` matches the filename's four-digit prefix, and ids are unique.
  - `status` is one of the four declared states.
  - a `superseded` ADR names its `superseded-by`, and a non-superseded one does not.
  - supersession is reciprocal: if A supersedes B, B is superseded-by A.
  - every referenced id exists.
  - `title` agrees with the record's own `# ADR NNNN — ...` heading.
  - the frontmatter is present, complete, and carries no unknown key.
  - the committed index is in sync with all of the above.

Four of ADR 0000's five numbered rules are deliberately OUT of reach here, and
saying so is the point — an unstated gap reads as a check that exists:

  - *status only moves forward* and *an accepted ADR is never rewritten* compare a
    record against its own past, which a snapshot does not have.
  - *numbers are permanent* needs the set of ids ever used, not the set present.
  - *one decision per record* is a judgment call; a heuristic for it would refuse
    honest records.

Those four are enforced by review, not by this script.

Standard library only, and runs on Python 3.9+ — deliberately wider than the 3.12+
floor ADR 0008 sets for the adapter, since docs tooling should not be the thing that
stops working on an older interpreter. The frontmatter parser is deliberately strict
and minimal rather than a YAML implementation: it accepts exactly the flat
`key: value` and inline-list shapes ADR 0000 declares, and refuses anything else
loudly. A permissive parser here would silently accept malformed frontmatter and
produce a wrong index, which is worse than no index.

Usage:
    python3 scripts/gen_adr_index.py            # write the index
    python3 scripts/gen_adr_index.py --check    # exit 1 if stale or invalid
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ADR_DIR = Path(__file__).resolve().parent.parent / "docs" / "adr"
INDEX = ADR_DIR / "README.md"

STATUSES = ("proposed", "accepted", "superseded", "deprecated")
FILENAME_RE = re.compile(r"^(\d{4})-[a-z0-9]+(?:-[a-z0-9]+)*\.md$")
SCALAR_KEYS = ("id", "title", "status", "date", "superseded-by")
LIST_KEYS = ("tags", "supersedes")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

GENERATED_NOTE = (
    "<!-- Generated by scripts/gen_adr_index.py. Do not edit by hand; "
    "edit the ADRs' frontmatter and regenerate. -->"
)


class AdrError(Exception):
    """A malformed ADR or a broken rule. Carries a message fit to print."""


def _document_parts(text: str, name: str) -> tuple[str, str]:
    """(frontmatter block, body). PRIVATE — the pair never crosses a public boundary.

    Both public readers take one thing and return one thing. That is the lesson of a
    real defect: a public `(block, body)` return was once spread into
    `parse_frontmatter(block, name)`, passing the body where the filename belonged, so
    every parse error printed the whole document instead of naming the file.
    """
    if not text.startswith("---\n"):
        raise AdrError(f"{name}: no YAML frontmatter (file must start with '---')")
    end = text.find("\n---\n", 3)
    if end == -1:
        raise AdrError(f"{name}: frontmatter is not closed by a '---' line")
    return text[4:end], text[end + 5 :]


def split_frontmatter(text: str, name: str) -> str:
    """The frontmatter block alone, or raise."""
    return _document_parts(text, name)[0]


HEADING_RE = re.compile(r"#[ \t]+ADR[ \t]+(\d{4})[ \t]+\u2014[ \t]+(.+?)[ \t]*")


def heading_of(text: str, name: str) -> tuple[str, str]:
    """The `# ADR NNNN — <title>` heading's id and title, or raise.

    The heading must be the FIRST non-blank line of the BODY. Both halves are
    load-bearing, and each closes a way this check can be fooled:

    - **Of the body.** Scanning the whole document let a `#` comment inside the
      frontmatter pose as the heading, so a record whose real heading had been
      deleted was accepted — fail-open, and precisely the silent acceptance this
      check exists to close.
    - **First.** Anywhere-in-the-body would match a heading quoted inside a fenced
      example — which ADR 0000 itself contains — refusing an honest record and
      naming the quoted id.

    All eleven records already satisfy it, so the strict form costs nothing now and
    is what a new record gets written against.
    """
    body = _document_parts(text, name)[1]
    first = next((line for line in body.splitlines() if line.strip()), "")
    m = HEADING_RE.fullmatch(first.strip())
    if not m:
        raise AdrError(
            f"{name}: the body must open with its `# ADR NNNN \u2014 <title>` heading; "
            f"found {first.strip()[:60]!r}. ADR 0000 requires it, and its title is what "
            "the frontmatter title is checked against."
        )
    return m.group(1), m.group(2)


def parse_frontmatter(block: str, name: str) -> dict[str, object]:
    """Parse the flat key/value + inline-list shape ADR 0000 declares."""
    out: dict[str, object] = {}
    for lineno, raw in enumerate(block.splitlines(), start=2):
        line = raw.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            raise AdrError(f"{name}:{lineno}: not a 'key: value' line: {line!r}")
        key, _, value = line.partition(":")
        key, value = key.strip(), value.strip()
        if key in out:
            raise AdrError(f"{name}:{lineno}: duplicate key {key!r}")
        if key in LIST_KEYS:
            if not (value.startswith("[") and value.endswith("]")):
                raise AdrError(
                    f"{name}:{lineno}: {key!r} must be an inline list, e.g. [a, b] or []"
                )
            inner = value[1:-1].strip()
            out[key] = (
                [v.strip() for v in inner.split(",") if v.strip()] if inner else []
            )
        elif key in SCALAR_KEYS:
            out[key] = value
        else:
            raise AdrError(f"{name}:{lineno}: unknown frontmatter key {key!r}")
    missing = [k for k in (*SCALAR_KEYS, *LIST_KEYS) if k not in out]
    if missing:
        raise AdrError(f"{name}: missing frontmatter key(s): {', '.join(missing)}")
    return out


def load() -> list[dict[str, object]]:
    """Every ADR, parsed and individually checked, ordered by id."""
    adrs: list[dict[str, object]] = []
    seen: dict[str, str] = {}
    for path in sorted(ADR_DIR.glob("*.md")):
        if path.name == "README.md":
            continue
        m = FILENAME_RE.match(path.name)
        if not m:
            raise AdrError(f"{path.name}: filename must be NNNN-lowercase-slug.md")
        raw = path.read_text(encoding="utf-8")
        block = split_frontmatter(raw, path.name)
        fm = parse_frontmatter(block, path.name)
        heading_id, heading_title = heading_of(raw, path.name)
        if heading_id != fm["id"]:
            raise AdrError(
                f"{path.name}: heading id {heading_id!r} disagrees with frontmatter "
                f"id {fm['id']!r}"
            )
        if heading_title != fm["title"]:
            raise AdrError(
                f"{path.name}: frontmatter title {fm['title']!r} disagrees with the "
                f"body heading {heading_title!r}. ADR 0000 requires them to match; "
                "a drifted title renders a wrong index that every other check passes."
            )
        if fm["id"] != m.group(1):
            raise AdrError(
                f"{path.name}: frontmatter id {fm['id']!r} != filename prefix {m.group(1)!r}"
            )
        if fm["status"] not in STATUSES:
            raise AdrError(
                f"{path.name}: status {fm['status']!r} is not one of {', '.join(STATUSES)}"
            )
        if not DATE_RE.match(str(fm["date"])):
            raise AdrError(f"{path.name}: date {fm['date']!r} is not YYYY-MM-DD")
        if (prev := seen.get(str(fm["id"]))) is not None:
            raise AdrError(f"{path.name}: id {fm['id']} already used by {prev}")
        seen[str(fm["id"])] = path.name
        fm["file"] = path.name
        adrs.append(fm)
    if not adrs:
        raise AdrError(f"no ADRs found in {ADR_DIR}")
    return sorted(adrs, key=lambda a: str(a["id"]))


def check_links(adrs: list[dict[str, object]]) -> None:
    """The supersession rules — the ones that need the whole set to check."""
    by_id = {str(a["id"]): a for a in adrs}
    for a in adrs:
        name, sb = a["file"], str(a["superseded-by"])
        for target in a["supersedes"]:  # type: ignore[union-attr]
            if target not in by_id:
                raise AdrError(f"{name}: supersedes unknown id {target!r}")
            if str(by_id[target]["superseded-by"]) != str(a["id"]):
                raise AdrError(
                    f"{name}: supersedes {target}, but {by_id[target]['file']} does not "
                    f"name {a['id']} as its superseded-by (supersession is reciprocal)"
                )
        if a["status"] == "superseded":
            if sb == "none":
                raise AdrError(
                    f"{name}: status is superseded but superseded-by is 'none'"
                )
            if sb not in by_id:
                raise AdrError(f"{name}: superseded-by unknown id {sb!r}")
            if str(a["id"]) not in by_id[sb]["supersedes"]:  # type: ignore[operator]
                raise AdrError(
                    f"{name}: superseded-by {sb}, but {by_id[sb]['file']} does not list "
                    f"{a['id']} in its supersedes (supersession is reciprocal)"
                )
        elif sb != "none":
            raise AdrError(
                f"{name}: names superseded-by {sb!r} but status is {a['status']!r}, "
                "not 'superseded'"
            )


def cell(value: str) -> str:
    """One table cell's text, safe to place between pipes.

    An unescaped `|` in a title or tag ends the cell early: the row silently renders
    with the wrong number of columns while every validation still passes and --check
    reports the index up to date. That is the silent-wrong-index failure this script
    exists to prevent, arriving through the renderer instead of the parser.
    """
    return value.replace("|", r"\|")


def render(adrs: list[dict[str, object]]) -> str:
    live = [a for a in adrs if a["status"] in ("proposed", "accepted")]
    retired = [a for a in adrs if a["status"] in ("superseded", "deprecated")]

    def rows(items: list[dict[str, object]], retired_cols: bool) -> list[str]:
        out = []
        for a in items:
            link = f"[{cell(str(a['id']))}]({a['file']})"
            tags = ", ".join(f"`{cell(str(t))}`" for t in a["tags"]) or "—"  # type: ignore[union-attr]
            if retired_cols:
                sb = a["superseded-by"]
                replaced = (
                    f"[{sb}]({next(x['file'] for x in adrs if x['id'] == sb)})"
                    if sb != "none"
                    else "—"
                )
                out.append(
                    f"| {link} | {cell(str(a['title']))} | {a['status']} | {replaced} |"
                )
            else:
                out.append(
                    f"| {link} | {cell(str(a['title']))} | {a['status']} | "
                    f"{a['date']} | {tags} |"
                )
        return out

    lines = [
        "# Architecture decisions",
        "",
        GENERATED_NOTE,
        "",
        "One decision per record. How these are written, and the rules the states follow,",
        "are in [ADR 0000](0000-record-architecture-decisions.md).",
        "",
        "## In force",
        "",
        "| # | Decision | Status | Date | Tags |",
        "|---|---|---|---|---|",
        *rows(live, retired_cols=False),
    ]
    if retired:
        lines += [
            "",
            "## No longer in force",
            "",
            "Kept deliberately: a decision that was reversed carries the reason the first",
            "answer looked right.",
            "",
            "| # | Decision | Status | Replaced by |",
            "|---|---|---|---|",
            *rows(retired, retired_cols=True),
        ]
    lines += ["", f"{len(adrs)} record(s).", ""]
    return "\n".join(lines)


def main() -> int:
    # `python3 -OO` strips docstrings, so __doc__ is None there.
    summary = (__doc__ or "Generate and validate the ADR index.").splitlines()[0]
    ap = argparse.ArgumentParser(description=summary)
    ap.add_argument(
        "--check",
        action="store_true",
        help="validate and report whether the index is stale; write nothing",
    )
    args = ap.parse_args()
    try:
        adrs = load()
        check_links(adrs)
        want = render(adrs)
    except AdrError as exc:
        print(f"adr: {exc}", file=sys.stderr)
        return 1

    have = INDEX.read_text(encoding="utf-8") if INDEX.exists() else None
    if args.check:
        if have != want:
            state = "missing" if have is None else "stale"
            print(
                f"adr: {INDEX.relative_to(ADR_DIR.parent.parent)} is {state} — "
                "run `python3 scripts/gen_adr_index.py`",
                file=sys.stderr,
            )
            return 1
        print(f"adr: {len(adrs)} record(s), index up to date")
        return 0

    if have == want:
        print(f"adr: {len(adrs)} record(s), index already up to date")
        return 0
    INDEX.write_text(want, encoding="utf-8")
    print(
        f"adr: {len(adrs)} record(s), wrote {INDEX.relative_to(ADR_DIR.parent.parent)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
